<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Builds a DSL Store, which is not safe to use concurrently. See Directory.Build.props. -->
    <UsesDslStore>true</UsesDslStore>
    <RootNamespace>Microsoft.Data.Entity.Tests.Design.Dsl</RootNamespace>
    <AssemblyName>Microsoft.Data.Entity.Tests.Design.Dsl</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Modeling.Sdk" />
    <PackageReference Include="Microsoft.VisualStudio.Modeling.Sdk.Diagrams" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Data.Entity.Design.Dsl\Microsoft.Data.Entity.Design.Dsl.csproj" />
    <ProjectReference Include="..\Microsoft.Data.Entity.Design.Model\Microsoft.Data.Entity.Design.Model.csproj" />
    <ProjectReference Include="..\Microsoft.Data.Entity.Design.VersioningFacade\Microsoft.Data.Entity.Design.VersioningFacade.csproj" />
    <ProjectReference Include="..\Microsoft.Data.Tools.Design.XmlCore\Microsoft.Data.Tools.Design.XmlCore.csproj" />
    <ProjectReference Include="..\Microsoft.VisualStudio.Data.Entity.Design\Microsoft.VisualStudio.Data.Entity.Design.csproj" />
    <ProjectReference Include="..\Microsoft.VisualStudio.Data.Tools.Design.XmlCore\Microsoft.VisualStudio.Data.Tools.Design.XmlCore.csproj" />
  </ItemGroup>

</Project>
