//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Data.Entity.XmlDesigner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlDesignerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlDesignerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Data.Entity.XmlDesigner.XmlDesignerResources", typeof(XmlDesignerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactoring operation has been canceled..
        /// </summary>
        internal static string Dialog_CancelRefactoring {
            get {
                return ResourceManager.GetString("Dialog_CancelRefactoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply changes to file {0}..
        /// </summary>
        internal static string Error_FailedApplyChangeToFile {
            get {
                return ResourceManager.GetString("Error_FailedApplyChangeToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the preview window..
        /// </summary>
        internal static string Error_FailedInvokePreviewWindow {
            get {
                return ResourceManager.GetString("Error_FailedInvokePreviewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refactoring operation has failed.  {0}.
        /// </summary>
        internal static string Error_FailedOperation {
            get {
                return ResourceManager.GetString("Error_FailedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check out files..
        /// </summary>
        internal static string Error_FailedToCheckOut {
            get {
                return ResourceManager.GetString("Error_FailedToCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactoring Error.
        /// </summary>
        internal static string ErrorDialog_Title {
            get {
                return ResourceManager.GetString("ErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the text buffer from file {0}..
        /// </summary>
        internal static string Exception_CannotGetTextBuffer {
            get {
                return ResourceManager.GetString("Exception_CannotGetTextBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are duplicate changes for file {0}..
        /// </summary>
        internal static string Exception_DuplicateChanges {
            get {
                return ResourceManager.GetString("Exception_DuplicateChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the changed file {0}..
        /// </summary>
        internal static string Exception_FailedToSaveFile {
            get {
                return ResourceManager.GetString("Exception_FailedToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for reference(s).
        /// </summary>
        internal static string FindReferences_Heading {
            get {
                return ResourceManager.GetString("FindReferences_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;Up&quot; and &quot;Down&quot; arrows to access the list items..
        /// </summary>
        internal static string MappingDetails_Up_And_Down {
            get {
                return ResourceManager.GetString("MappingDetails_Up_And_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled background process at iteration {0}/{1}. Most recent status message was:
        ///
        ///{2}.
        /// </summary>
        internal static string ProgressDialogBackgroundJobCancellationMessage {
            get {
                return ResourceManager.GetString("ProgressDialogBackgroundJobCancellationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background job failed at iteration {0}/{1}.
        ///Caught exception of type {2} with message {3} and stack trace {4}.
        /// </summary>
        internal static string ProgressDialogBackgroundJobErrorMessage {
            get {
                return ResourceManager.GetString("ProgressDialogBackgroundJobErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With inner exception of type {0} with message {1} and stack trace {2}.
        /// </summary>
        internal static string ProgressDialogBackgroundJobInnerExceptionErrorMessage {
            get {
                return ResourceManager.GetString("ProgressDialogBackgroundJobInnerExceptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ProgressDialogCloseInterruptButtonCloseText {
            get {
                return ResourceManager.GetString("ProgressDialogCloseInterruptButtonCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ProgressDialogCloseInterruptButtonInterruptText {
            get {
                return ResourceManager.GetString("ProgressDialogCloseInterruptButtonInterruptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ProgressDialogStatusLabelText {
            get {
                return ResourceManager.GetString("ProgressDialogStatusLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor.
        /// </summary>
        internal static string RefactorDialog_Title {
            get {
                return ResourceManager.GetString("RefactorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes are required.
        /// </summary>
        internal static string RefactoringOperation_NoChanges {
            get {
                return ResourceManager.GetString("RefactoringOperation_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This refactoring has no changes to preview..
        /// </summary>
        internal static string RefactoringOperation_NoChangesToPreview {
            get {
                return ResourceManager.GetString("RefactoringOperation_NoChangesToPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes to preview..
        /// </summary>
        internal static string RefactoringOperation_NoChangesToPreviewTitle {
            get {
                return ResourceManager.GetString("RefactoringOperation_NoChangesToPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service instances must inherit from or implement {0}..
        /// </summary>
        internal static string ServiceProvider_InvalidServiceInstance {
            get {
                return ResourceManager.GetString("ServiceProvider_InvalidServiceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} already exists in the service container..
        /// </summary>
        internal static string ServiceProvider_ServiceAlreadyExists {
            get {
                return ResourceManager.GetString("ServiceProvider_ServiceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Node Type encountered in XmlReader..
        /// </summary>
        internal static string TreeBuilder_UnknownNodeType {
            get {
                return ResourceManager.GetString("TreeBuilder_UnknownNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value can be edited through a drop-down list.  Press Alt+Down Arrow to open the list..
        /// </summary>
        internal static string TridDes_ComboAccDesc {
            get {
                return ResourceManager.GetString("TridDes_ComboAccDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value can be edited through a dialog box.  Press Alt+Down Arrow to open the dialog box..
        /// </summary>
        internal static string TridDes_LauncherAccDesc {
            get {
                return ResourceManager.GetString("TridDes_LauncherAccDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTD nodes cannot be edited..
        /// </summary>
        internal static string VanillaProvider_DtdNodesReadOnly {
            get {
                return ResourceManager.GetString("VanillaProvider_DtdNodesReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction already completed..
        /// </summary>
        internal static string VanillaProvider_TxAlreadyCompleted {
            get {
                return ResourceManager.GetString("VanillaProvider_TxAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert a child of type &apos;{0}&apos; into a parent of type &apos;{1}&apos;..
        /// </summary>
        internal static string BadInsertBadChildType {
            get {
                return ResourceManager.GetString("BadInsertBadChildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert a child of type &apos;{0}&apos; into a parent of type &apos;{1}&apos; because the child already  [rest of string was truncated]&amp;quot;;.
        /// </summary>
        internal static string BadInsertChildAlreadyExists {
            get {
                return ResourceManager.GetString("BadInsertChildAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the child &apos;{0}&apos; from the node &apos;{1}&apos; because the node is not the child&apos;s pare [rest of string was truncated]&amp;quot;;.
        /// </summary>
        internal static string BadRemoveChildNotParent {
            get {
                return ResourceManager.GetString("BadRemoveChildNotParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Center.
        /// </summary>
        internal static string DesignerViewCommandsText {
            get {
                return ResourceManager.GetString("DesignerViewCommandsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] = {1} ({2}).
        /// </summary>
        internal static string ExplorerSearchResults_IndividualFormat {
            get {
                return ResourceManager.GetString("ExplorerSearchResults_IndividualFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Search Results = {0} Results = [{1}] Index of Previous = {2} Index of Next = {3} [rest of string was truncated]&amp;quot;;.
        /// </summary>
        internal static string ExplorerSearchResults_OverallFormat {
            get {
                return ResourceManager.GetString("ExplorerSearchResults_OverallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} found).
        /// </summary>
        internal static string NumOfSearchResultsFound {
            get {
                return ResourceManager.GetString("NumOfSearchResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string PropertyWindow_Value_False {
            get {
                return ResourceManager.GetString("PropertyWindow_Value_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string PropertyWindow_Value_True {
            get {
                return ResourceManager.GetString("PropertyWindow_Value_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename {0}.
        /// </summary>
        internal static string RenameTransactionNameFormat {
            get {
                return ResourceManager.GetString("RenameTransactionNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is OneWay.
        /// </summary>
        internal static string SwitchConverterErrorMessage {
            get {
                return ResourceManager.GetString("SwitchConverterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0}.
        /// </summary>
        internal static string Tx_PropertyChangeUndoString {
            get {
                return ResourceManager.GetString("Tx_PropertyChangeUndoString", resourceCulture);
            }
        }
    }
}
