//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Data.Entity.Design.XmlEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlEngineResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlEngineResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Data.Entity.Design.XmlEngine.XmlEngineResources", typeof(XmlEngineResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid for this converter.
        /// </summary>
        internal static string ConversionExceptionMessage {
            get {
                return ResourceManager.GetString("ConversionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid for attribute &apos;{1}&apos;. Please enter a different value..
        /// </summary>
        internal static string ConverterIncorrectValueForAttribute {
            get {
                return ResourceManager.GetString("ConverterIncorrectValueForAttribute", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}: {1}.
        /// </summary>
        internal static string Error_Message_With_Error_Code_Prefix {
            get {
                return ResourceManager.GetString("Error_Message_With_Error_Code_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resolving item &apos;{0}&apos;. The exception message is: &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorResolvingItem {
            get {
                return ResourceManager.GetString("ErrorResolvingItem", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled because the following files are not editable: &apos;{0}&apos;.
        /// </summary>
        internal static string FileNotEditableErrorMessage {
            get {
                return ResourceManager.GetString("FileNotEditableErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string INVALID_NC_NAME_CHAR {
            get {
                return ResourceManager.GetString("INVALID_NC_NAME_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} cannot be duplicated in this context. Please choose another name..
        /// </summary>
        internal static string NAME_NOT_UNIQUE {
            get {
                return ResourceManager.GetString("NAME_NOT_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string NoneDisplayValueUsedForUX {
            get {
                return ResourceManager.GetString("NoneDisplayValueUsedForUX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol &apos;{0}&apos; has already been defined..
        /// </summary>
        internal static string NORMALIZE_DUPLICATE_SYMBOL_DEFINED {
            get {
                return ResourceManager.GetString("NORMALIZE_DUPLICATE_SYMBOL_DEFINED", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string PropertyWindow_Category_General {
            get {
                return ResourceManager.GetString("PropertyWindow_Category_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PropertyWindow_DisplayName_Name {
            get {
                return ResourceManager.GetString("PropertyWindow_DisplayName_Name", resourceCulture);
            }
        }
        
        
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Node Type encountered in XmlReader..
        /// </summary>
        internal static string TreeBuilder_UnknownNodeType {
            get {
                return ResourceManager.GetString("TreeBuilder_UnknownNodeType", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to DTD nodes cannot be edited..
        /// </summary>
        internal static string VanillaProvider_DtdNodesReadOnly {
            get {
                return ResourceManager.GetString("VanillaProvider_DtdNodesReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction already completed..
        /// </summary>
        internal static string VanillaProvider_TxAlreadyCompleted {
            get {
                return ResourceManager.GetString("VanillaProvider_TxAlreadyCompleted", resourceCulture);
            }
        }
    }
}
