<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Microsoft.VisualStudio.Data.Entity.Tests.Package</RootNamespace>
    <AssemblyName>Microsoft.VisualStudio.Data.Entity.Tests.Package</AssemblyName>
    <NoWarn>$(NoWarn);VSTHRD010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Data" />
    <Reference Include="System.Data.Entity" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Data.Core" />
    <PackageReference Include="Microsoft.VisualStudio.DataTools.Interop" />
    <PackageReference Include="Microsoft.VisualStudio.Interop" />
    <PackageReference Include="Microsoft.VisualStudio.Shell.15.0" />
    <PackageReference Include="Microsoft.VisualStudio.Shell.Design" />
    <PackageReference Include="Microsoft.VisualStudio.TemplateWizardInterface" />
    <PackageReference Include="Microsoft.VisualStudio.TextTemplating" />
    <PackageReference Include="Microsoft.VisualStudio.TextTemplating.Interfaces" />
    <PackageReference Include="Microsoft.VisualStudio.Utilities" />
    <PackageReference Include="Microsoft.VSDesigner" />
    <PackageReference Include="Microsoft.WizardFramework" />
    <PackageReference Include="VsWebSite.Interop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.VisualStudio.Data.Entity.Extensibility\Microsoft.VisualStudio.Data.Entity.Extensibility.csproj" />
    <ProjectReference Include="..\Microsoft.VisualStudio.Data.Entity.Package\Microsoft.VisualStudio.Data.Entity.Package.csproj" />
    <ProjectReference Include="..\Microsoft.Data.Entity.Design.EntityFramework\Microsoft.Data.Entity.Design.EntityFramework.csproj" />
    <ProjectReference Include="..\Microsoft.Data.Entity.Tests.Design\Microsoft.Data.Entity.Tests.Design.csproj">
      <!-- Reference for TestHelpers only -->
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
    <ProjectReference Include="..\Microsoft.VisualStudio.Data.Entity.EdmxDesigner\Microsoft.VisualStudio.Data.Entity.EdmxDesigner.csproj" />
  </ItemGroup>

</Project>
