#:package Microsoft.CodeAnalysis.CSharp@4.14.0

// Catalogs every type in every .cs file: name, kind, generated status, whether the file violates
// one-type-per-file, and the destination name under the container rename.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

var root = @"D:\GitHub\EasyAF.EntityDesigner\src";
var outPath = @"D:\GitHub\EasyAF.EntityDesigner\specs\_type-catalog.md";

// Types that exist in BOTH Design.Model and Design.Dsl. The Model-side copy takes an Edmx prefix.
var collisions = new HashSet<string>(StringComparer.Ordinal)
{
    "Association", "AssociationConnector", "ComplexProperty", "EntityType", "EntityTypeShape",
    "InheritanceConnector", "NavigationProperty", "Property", "PropertyBase", "ScalarProperty",
};

var files = Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories)
    .Where(f => !f.Contains(@"\obj\") && !f.Contains(@"\bin\"))
    .OrderBy(f => f, StringComparer.OrdinalIgnoreCase)
    .ToList();

var rows = new List<Row>();
var skipped = new List<string>();

foreach (var file in files)
{
    string text;
    try { text = File.ReadAllText(file); }
    catch (Exception ex) { skipped.Add($"{file}: {ex.Message}"); continue; }

    var rel = Path.GetRelativePath(root, file).Replace('\\', '/');
    var project = rel.Split('/')[0];
    var fileName = Path.GetFileNameWithoutExtension(file);

    var isGenerated =
        rel.Contains("/GeneratedCode/", StringComparison.OrdinalIgnoreCase) ||
        fileName.EndsWith(".Designer", StringComparison.OrdinalIgnoreCase) ||
        fileName.EndsWith(".g", StringComparison.OrdinalIgnoreCase) ||
        fileName.EndsWith(".g.i", StringComparison.OrdinalIgnoreCase) ||
        text.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase) ||
        text.Contains("This code was generated by a tool", StringComparison.OrdinalIgnoreCase);

    var tree = CSharpSyntaxTree.ParseText(text);

    // A delegate is a type, but DelegateDeclarationSyntax does not derive from BaseTypeDeclarationSyntax.
    // Leaving it out undercounts files - ProviderEvents.cs reported 10 types and actually held 21.
    var declared = tree.GetRoot().DescendantNodes()
        .Where(n => n is BaseTypeDeclarationSyntax or DelegateDeclarationSyntax)
        .Cast<MemberDeclarationSyntax>()
        .ToList();

    if (declared.Count == 0)
    {
        rows.Add(new Row(project, rel, fileName, "(none)", "-", isGenerated, 0, false, "-", "no types"));
        continue;
    }

    var topLevel = declared.Where(d => d.Parent is BaseNamespaceDeclarationSyntax or CompilationUnitSyntax).ToList();

    foreach (var decl in declared)
    {
        var name = decl switch
        {
            BaseTypeDeclarationSyntax b => b.Identifier.Text,
            DelegateDeclarationSyntax d => d.Identifier.Text,
            _ => "?",
        };
        var nested = !(decl.Parent is BaseNamespaceDeclarationSyntax or CompilationUnitSyntax);

        var kind = decl switch
        {
            ClassDeclarationSyntax c => c.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)) ? "partial class" : "class",
            StructDeclarationSyntax => "struct",
            InterfaceDeclarationSyntax => "interface",
            EnumDeclarationSyntax => "enum",
            RecordDeclarationSyntax => "record",
            DelegateDeclarationSyntax => "delegate",
            _ => decl.Kind().ToString(),
        };

        // Destination name.
        var (newName, note) = Destination(project, rel, name, isGenerated);

        // Extraction needed? Non-generated, top-level, and either not alone in the file or misnamed file.
        var needsExtract = !isGenerated && !nested && topLevel.Count > 1;

        rows.Add(new Row(project, rel, fileName, name, kind, isGenerated, topLevel.Count, needsExtract, newName, note));
    }
}

(string, string) Destination(string project, string rel, string name, bool generated)
{
    if (project == "Microsoft.Data.Entity.Design.Edmx" && collisions.Contains(name))
        return ("Edmx" + name, "collides with Diagrams");

    if (name.StartsWith("MicrosoftDataEntityDesign", StringComparison.Ordinal))
        return ("TBD", "driven by DslDefinition.dsl Name attribute");

    if (name.Contains("Escher", StringComparison.OrdinalIgnoreCase))
        return ("TBD", "carries the retired Escher codename");

    if (name.Contains("XmlCore", StringComparison.OrdinalIgnoreCase) ||
        name.Contains("XmlDesignerBase", StringComparison.OrdinalIgnoreCase) ||
        name.Contains("VSXmlDesignerBase", StringComparison.OrdinalIgnoreCase))
        return ("TBD", "names a retired container");

    return (name, generated ? "unchanged (generated)" : "unchanged");
}

// ---- emit ----

var sb = new StringBuilder();
sb.AppendLine("# Type catalog");
sb.AppendLine();
sb.AppendLine("Generated by `tools/type-catalog.cs`. Every type in every `.cs` file under `src/`, excluding `obj/` and `bin/`.");
sb.AppendLine();
sb.AppendLine($"- Files scanned: **{files.Count}**");
sb.AppendLine($"- Type declarations: **{rows.Count(r => r.Type != "(none)")}**");
sb.AppendLine($"- Files with no types: **{rows.Count(r => r.Type == "(none)")}**");
sb.AppendLine($"- Non-generated files holding more than one top-level type: **{rows.Where(r => r.NeedsExtract).Select(r => r.File).Distinct().Count()}**");
sb.AppendLine($"- Types with a decided rename: **{rows.Count(r => r.NewName != r.Type && r.NewName != "TBD" && r.Type != "(none)")}**");
sb.AppendLine($"- Types flagged TBD: **{rows.Count(r => r.NewName == "TBD")}**");
if (skipped.Count > 0) sb.AppendLine($"- **Unreadable files: {skipped.Count}**");
sb.AppendLine();

sb.AppendLine("## Action summary");
sb.AppendLine();
sb.AppendLine("| Note | Types |");
sb.AppendLine("|---|---:|");
foreach (var g in rows.Where(r => r.Type != "(none)").GroupBy(r => r.Note).OrderByDescending(g => g.Count()))
    sb.AppendLine($"| {g.Key} | {g.Count()} |");
sb.AppendLine();

sb.AppendLine("## Files needing extraction (one type per file)");
sb.AppendLine();
sb.AppendLine("Non-generated files declaring more than one top-level type.");
sb.AppendLine();
sb.AppendLine("| File | Top-level types | Names |");
sb.AppendLine("|---|---:|---|");
foreach (var g in rows.Where(r => r.NeedsExtract).GroupBy(r => r.File).OrderBy(g => g.Key))
{
    var names = string.Join(", ", g.Select(r => $"`{r.Type}`"));
    sb.AppendLine($"| `{g.Key}` | {g.First().TopLevelCount} | {names} |");
}
sb.AppendLine();

sb.AppendLine("## Full catalog");
sb.AppendLine();

foreach (var proj in rows.Select(r => r.Project).Distinct().OrderBy(p => p, StringComparer.OrdinalIgnoreCase))
{
    var pr = rows.Where(r => r.Project == proj).ToList();
    sb.AppendLine($"### {proj}");
    sb.AppendLine();
    sb.AppendLine($"{pr.Select(r => r.File).Distinct().Count()} files, {pr.Count(r => r.Type != "(none)")} types.");
    sb.AppendLine();
    sb.AppendLine("| File | Type | Kind | Gen | Extract | Destination | Note |");
    sb.AppendLine("|---|---|---|:-:|:-:|---|---|");

    foreach (var r in pr.OrderBy(r => r.File, StringComparer.OrdinalIgnoreCase).ThenBy(r => r.Type, StringComparer.OrdinalIgnoreCase))
    {
        var shortFile = r.File.Substring(proj.Length).TrimStart('/');
        var dest = r.NewName == r.Type ? "—" : $"`{r.NewName}`";
        sb.AppendLine($"| `{shortFile}` | `{r.Type}` | {r.Kind} | {(r.Generated ? "Y" : "")} | {(r.NeedsExtract ? "**Y**" : "")} | {dest} | {r.Note} |");
    }
    sb.AppendLine();
}

File.WriteAllText(outPath, sb.ToString());

Console.WriteLine($"files scanned        : {files.Count}");
Console.WriteLine($"type declarations    : {rows.Count(r => r.Type != "(none)")}");
Console.WriteLine($"files with no types  : {rows.Count(r => r.Type == "(none)")}");
Console.WriteLine($"files needing extract: {rows.Where(r => r.NeedsExtract).Select(r => r.File).Distinct().Count()}");
Console.WriteLine($"decided renames      : {rows.Count(r => r.NewName != r.Type && r.NewName != "TBD" && r.Type != "(none)")}");
Console.WriteLine($"TBD                  : {rows.Count(r => r.NewName == "TBD")}");
Console.WriteLine($"unreadable           : {skipped.Count}");
foreach (var s in skipped) Console.WriteLine("  " + s);
Console.WriteLine($"wrote {outPath}");

record Row(string Project, string File, string FileName, string Type, string Kind, bool Generated, int TopLevelCount, bool NeedsExtract, string NewName, string Note);
