// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the MIT license.  See License.txt in the project root for license information.

namespace Microsoft.VisualStudio.Data.Entity.Extensibility
{

    /// <summary>
    /// Exposes methods for customizing the generation of .edmx files.
    /// </summary>
    /// <example>
    /// A generation extension is discovered through MEF and needs no metadata attribute beyond the export itself.
    /// <code>
    /// [Export(typeof(IModelGenerationExtension))]
    /// public class StampModelVersion : IModelGenerationExtension
    /// {
    ///     public void OnAfterModelGenerated(ModelGenerationExtensionContext context)
    ///     {
    ///         MyAnnotations.Stamp(context.CurrentDocument, context.EntityFrameworkVersion);
    ///     }
    ///
    ///     public void OnAfterModelUpdated(UpdateModelExtensionContext context)
    ///     {
    ///         // context.OriginalDocument is the model as it was before the wizard ran, and
    ///         // context.UpdateModelDocument is the merged result. Re-apply anything the merge lost.
    ///         MyAnnotations.Reapply(context.OriginalDocument, context.CurrentDocument);
    ///     }
    /// }
    /// </code>
    /// </example>
    /// <remarks>
    /// Implement this interface to post-process the EDMX the Entity Data Model Wizard produces from a database, before it is
    /// written into the project. This is the hook to use when a model needs custom annotations, naming conventions or extra
    /// content applied at reverse-engineering time rather than on every load and save.
    /// <para>
    /// Every registered generation extension is invoked in turn and each one sees the document as the previous extension left
    /// it. Only <c>CurrentDocument</c> may be modified; touching any other document supplied on the context throws an
    /// <see cref="System.InvalidOperationException" />. An exception thrown out of either method is caught by the designer and
    /// reported to the user in a dialog; the remaining extensions still run.
    /// </para>
    /// </remarks>
    public interface IModelGenerationExtension
    {

        #region Public Methods

        /// <summary>
        /// Defines custom functionality that is executed after an .edmx file has been generated by the Entity Data Model Wizard.
        /// </summary>
        /// <param name="context">Provides file and project information.</param>
        /// <remarks>
        /// Called when a new model has been reverse-engineered from a database and before it is saved into the project. Apply
        /// changes to <see cref="ModelGenerationExtensionContext.CurrentDocument" />;
        /// <see cref="ModelGenerationExtensionContext.GeneratedDocument" /> is the untouched wizard output and is read-only.
        /// </remarks>
        void OnAfterModelGenerated(ModelGenerationExtensionContext context);

        /// <summary>
        /// Defines functionality that is executed after an .edmx file has been updated by the Update Model Wizard.
        /// </summary>
        /// <param name="context">Provides file and project information.</param>
        /// <remarks>
        /// Called when an existing model has been refreshed from the database. In addition to the documents available during
        /// generation, the context exposes <see cref="UpdateModelExtensionContext.OriginalDocument" /> (the model before the
        /// wizard ran) and <see cref="UpdateModelExtensionContext.UpdateModelDocument" /> (the merged result), which is where an
        /// extension normally looks to re-apply information the merge did not carry forward. Only
        /// <see cref="ModelGenerationExtensionContext.CurrentDocument" /> may be modified.
        /// </remarks>
        void OnAfterModelUpdated(UpdateModelExtensionContext context);

        #endregion

    }

}
