// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the MIT license.  See License.txt in the project root for license information.

using System;
using System.Xml.Linq;

namespace Microsoft.VisualStudio.Data.Entity.Extensibility
{

    /// <summary>
    /// Provides file and project information to Visual Studio extensions that extend the .edmx file generation process of the
    /// Entity Data Model Wizard.
    /// </summary>
    /// <remarks>
    /// Handed to <see cref="IModelGenerationExtension.OnAfterModelGenerated(ModelGenerationExtensionContext)" />. Only
    /// <see cref="CurrentDocument" /> may be modified; the other documents are supplied for comparison and throw if an extension
    /// tries to change them.
    /// </remarks>
    public abstract class ModelGenerationExtensionContext : ExtensionContext
    {

        #region Properties

        /// <summary>
        /// Represents the .edmx document to be modified.
        /// </summary>
        /// <value>The document that should be updated by extensions.</value>
        /// <remarks>
        /// This is the model generated from the database plus all modifications made by extensions that have already run, so
        /// each extension in the chain sees the output of the previous one. It is the only document on this context that an
        /// extension is allowed to modify.
        /// </remarks>
        public abstract XDocument CurrentDocument { get; }

        /// <summary>
        /// Represents the original .edmx file generated by the Entity Data Model Wizard.
        /// </summary>
        /// <value>The unmodified document produced by reverse-engineering the database.</value>
        /// <remarks>
        /// Read-only. Compare it against <see cref="CurrentDocument" /> to see what earlier extensions changed. Attempting to
        /// modify it throws an <see cref="InvalidOperationException" />.
        /// </remarks>
        public abstract XDocument GeneratedDocument { get; }

        /// <summary>
        /// The wizard that initiated the .edmx file generation or update process.
        /// </summary>
        /// <value>
        /// <see cref="WizardKind.Generate" /> when a new model is being created, or
        /// <see cref="WizardKind.UpdateModel" /> when an existing model is being refreshed.
        /// </value>
        public abstract WizardKind WizardKind { get; }

        #endregion

    }

}
